repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.0"
    hooks:
      - id: prettier
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
