[package]
name = "rust-ocpp"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Tommy Malmqvist <tommy.malmqvist@codelabs.se"]
edition = "2021"
keywords = ["ocpp", "ev", "csms"]
categories = ["library"]
exclude = ["/docs"]

[badges]
maintenance = { status = "experimental" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.19", features = ["serde"] }
rand = "0.8"
uuid = { version = "0.8", features = ["v4"] }
pretty_env_logger = "0.4.0"
log = "0.4"
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
mockall = "0.10.2"
